<?php
$userinfo=User::get_client_by_id($request->get('userid'));
$cert = $request->get_certificate_ref();
$docData = array( 
					"day" => $request->get_day(),
					"month" => get_month( $request->get_month() ),
					"year" => $request->get_year(),
					"name"=>$userinfo['userrealname'], 
					"age" => $userinfo['userage'],
					'nationality'=>$userinfo["usernationality"],
					'taxno'=>$userinfo["usertaxid"],
					'addrhouse'=>$userinfo["useraddrhouse"],
					'addrvillage'=>$userinfo["useraddrvillage"],
					'addrdrive'=>$userinfo["useraddrdrive"],
					'addrroad'=>$userinfo["useraddrroad"],
					'addrsubdistrict'=>$userinfo["useraddrsubdistrict"],
					'addrdistrict'=>$userinfo["useraddrdistrict"],
					'addrprovince'=>$userinfo["useraddrprovince"],
					'addrpostalcode'=>$userinfo["userpostalcode"],
					'addrphone'=>$userinfo["userphone"],
					'addrfax'=>$userinfo["userfax"],
					'productname'=>$request->get_data('productname'),
					'producthouse'=>$request->get_data('producthouse'),
					'productvillage'=>$request->get_data('productvillage'),
					'productdrive'=>$request->get_data('productdrive'),
					'productroad'=>$request->get_data('productroad'),
					'productsubdistrict'=>$request->get_data('productsubdistrict'),
					'productdistrict'=>$request->get_data('productdistrict'),
					'productprovince'=>$request->get_data('productprovince'),
					'productpostalcode'=>$request->get_data('productpostalcode'),
					'productphone'=>$request->get_data('productphone'),
					'productfax'=>$request->get_data('productfax'),
					'storename'=>$request->get_data('storename'),
					'storehouse'=>$request->get_data('storehouse'),
					'storevillage'=>$request->get_data('storevillage'),
					'storedrive'=>$request->get_data('storedrive'),
					'storeroad'=>$request->get_data('storeroad'),
					'storesubdistrict'=>$request->get_data('storesubdistrict'),
					'storedistrict'=>$request->get_data('storedistrict'),
					'storeprovince'=>$request->get_data('storeprovince'),
					'storepostalcode'=>$request->get_data('storepostalcode'),
					'storephone'=>$request->get_data('storephone'),
					'storefax'=>$request->get_data('storefax'),
					'storespecialist'=>$request->get_data('storespecialist'),
					'hazardno'=>$request->get_data('certidref'),
					
					'hazardname'=>$cert->get_data('hazardname'),
					'hazardformulation'=>$cert->get_data('hazardformulation'),
					'businessname'=>$cert->get_data('businessname'),
					
					'quantity'=>$request->get_data('quantity'),
					'note'=>$request->get_data('note'),
					'producerspecialist'=>$request->get_data('producerspecialist')
				);
				
?>