<?php
 	require_once('core/init.php');
	include(resolveHeader('includes/header.php'));

	$info2=array(
		'certid'=>'วอ.2-0001/2556',
		'department'=>'เกษตรค้าข้าว',
		'ministry'=>'เกษตรและสหกรณ์',
		'day'=>'12',
		'month'=>'มกราคม',
		'year'=>'2556',
		'certidref'=>'วอ./กษ./กวก.2-0001/2556',
		'name'=>'นายสุเทพ เทือกสุบรรณ',
		'nationality'=>'ไทย',
		'taxno'=>'5410500199',
		'addrhouse'=>'52',
		'addrvillage'=>'1',
		'addrdrive'=>'2',
		'addrroad'=>'เทพกระษัตรี',
		'addrsubdistrict'=>'เทพกระษัตรี',
		'addrdistrict'=>'ถลาง',
		'addrprovince'=>'ภูเก็ต',
		'addrpostalcode'=>'83110',
		'addrphone'=>'076311650',
		'addrfax'=>'076313535',
		'productname' => 'รติก๊าส',
		'producthouse'=>'52',
		'productvillage'=>'1',
		'productdrive'=>'2',
		'productroad'=>'เทพกระษัตรี',
		'productsubdistrict'=>'เทพกระษัตรี',
		'productdistrict'=>'ถลาง',
		'productprovince'=>'ภูเก็ต',
		'productpostalcode'=>'83110',
		'productphone'=>'076311650',
		'productfax'=>'076313535',
		'hazardname'=>'น้ำจากเทือกเขา',
		'hazardformulation'=>'H20',
		'businessname'=>'น้ำเปล่า',
		'quantity'=>'5 ถัง กับอีก 3 ขวด',
		'note'=>'มันลืนคอเหมือนดื่มอากาศ',
		'producerspecialist'=>'ทักษิณ ชินวัตร',
		'condition'=>'ต้องเขย่าก่อนดื่ม',
		'expday'=>'12',
		'expmonth'=>'มกราคม',
		'expyear'=>'2556',
		'officername'=>'สมรัก คำสิงค์',
		'productcertid'=>'วอ./กษ./กวก.2-0001/2556',
		'storename' => 'บ้านทองหยอด',
		'storehouse' => '100/10',
		'storevillage' => '51',
		'storedrive' => 'บ้านบึง 3',
		'storeroad' => 'งามวงวาน',
		'storesubdistrict' => 'มะขามป้อม',
		'storedistrict' => 'บางเขน',
		'storeprovince' => 'กทม.',
		'storepostalcode' => '10010',
		'storephone' => '075123321',
		'storefax' => '078123456',
		'storespecialist' => 'สนธิ ลิ้มทองกุล'
	);

	$info4=array(
		'certid'=>'วอ.4-0001/2556',
		'department'=>'เกษตรค้าข้าว',
		'ministry'=>'เกษตรและสหกรณ์',
		'day'=>'12',
		'month'=>'มกราคม',
		'year'=>'2556',
		'certidref'=>'วอ./กษ./กวก.2-0001/2556',
		'name'=>'นายสุเทพ เทือกสุบรรณ',
		'nationality'=>'ไทย',
		'taxno'=>'5410500199',
		'addrhouse'=>'52',
		'addrvillage'=>'1',
		'addrdrive'=>'2',
		'addrroad'=>'เทพกระษัตรี',
		'addrsubdistrict'=>'เทพกระษัตรี',
		'addrdistrict'=>'ถลาง',
		'addrprovince'=>'ภูเก็ต',
		'addrpostalcode'=>'83110',
		'addrphone'=>'076311650',
		'addrfax'=>'076313535',
		'hazardname'=>'น้ำจากเทือกเขา',
		'hazardformulation'=>'H20',
		'businessname'=>'น้ำเปล่า',
		'producer'=>'ทักษิณ ชินวัตร',
		'producerCountry'=>'ดูไบ',
		'quantity'=>'5 ถัง กบัอีก 3 ขวด',
		'note'=>'มันลืนคอเหมือนดื่มอากาศ',
		'condition'=>'ต้องเขย่าก่อนดื่ม',
		'expday'=>'12',
		'expmonth'=>'มกราคม',
		'expyear'=>'2556',
		'officername'=>'สมรัก คำสิงค์',
		'storehouse'=>'52',
		'storevillage'=>'1',
		'storedrive'=>'2',
		'storeroad'=>'เทพกระษัตรี',
		'storesubdistrict'=>'เทพกระษัตรี',
		'storedistrict'=>'ถลาง',
		'storeprovince'=>'ภูเก็ต',
		'storepostalcode'=>'83110',
		'storephone'=>'076311650',
		'storefax'=>'076313535',
		'storespecialist'=>'ดร. ภุชงค์ ชงไมโล'
	);

	$info6=array(
		'certid'=>'วอ.4-0001/2556',
		'department'=>'เกษตรค้าข้าว',
		'ministry'=>'เกษตรและสหกรณ์',
		'day'=>'12',
		'month'=>'มกราคม',
		'year'=>'2556',
		'certidref'=>'วอ./กษ./กวก.2-0001/2556',
		'name'=>'นายสุเทพ เทือกสุบรรณ',
		'nationality'=>'ไทย',
		'taxno'=>'5410500199',
		'addrhouse'=>'52',
		'addrvillage'=>'1',
		'addrdrive'=>'2',
		'addrroad'=>'เทพกระษัตรี',
		'addrsubdistrict'=>'เทพกระษัตรี',
		'addrdistrict'=>'ถลาง',
		'addrprovince'=>'ภูเก็ต',
		'addrpostalcode'=>'83110',
		'addrphone'=>'076311650',
		'addrfax'=>'076313535',
		'hazardname'=>'น้ำจากเทือกเขา',
		'hazardformulation'=>'H20',
		'businessname'=>'น้ำเปล่า',
		'orderCountry'=>'ดูไบ',
		'quantity'=>'5 ถัง กบัอีก 3 ขวด',
		'note'=>'มันลืนคอเหมือนดื่มอากาศ',
		'condition'=>'ต้องเขย่าก่อนดื่ม',
		'expday'=>'12',
		'expmonth'=>'มกราคม',
		'expyear'=>'2556',
		'officername'=>'สมรัก คำสิงค์',
		'certid1'=>'วอ.4-0007/2543',
		'storename'=>'บ้านนกนางแอ่น',
		'storehouse'=>'1/55',
		'storevillage'=>'3',
		'storedrive'=>'5',
		'storeroad'=>'พหลโยธิน',
		'storesubdistrict'=>'เทพกระษัตรี',
		'storedistrict'=>'ถลาง',
		'storeprovince'=>'ภูเก็ต',
		'storepostalcode'=>'83110',
		'storephone'=>'076311650',
		'storefax'=>'076313535',
		'storespecialist'=>'ดร. ภุชงค์ ชงไมโล'
	);

	$info8=array(
		'certid'=>'วอ.4-0001/2556',
		'department'=>'เกษตรค้าข้าว',
		'ministry'=>'เกษตรและสหกรณ์',
		'day'=>'12',
		'month'=>'มกราคม',
		'year'=>'2556',
		'name'=>'นายสุเทพ เทือกสุบรรณ',
		'nationality'=>'ไทย',
		'taxno'=>'5410500199',
		'addrhouse'=>'52',
		'addrvillage'=>'1',
		'addrdrive'=>'2',
		'addrroad'=>'เทพกระษัตรี',
		'addrsubdistrict'=>'เทพกระษัตรี',
		'addrdistrict'=>'ถลาง',
		'addrprovince'=>'ภูเก็ต',
		'addrpostalcode'=>'83110',
		'addrphone'=>'076311650',
		'addrfax'=>'076313535',
		'storename'=>'บ้านหลังเขา',
		'storehouse'=>'52',
		'storevillage'=>'1',
		'storedrive'=>'2',
		'storeroad'=>'เทพกระษัตรี',
		'storesubdistrict'=>'เทพกระษัตรี',
		'storedistrict'=>'ถลาง',
		'storeprovince'=>'ภูเก็ต',
		'storepostalcode'=>'83110',
		'storephone'=>'076311650',
		'storefax'=>'076313535',
		'storespecialist'=>'ดร. ภุชงค์ ชงไมโล',
		'quantity'=>'5 ถัง กบัอีก 3 ขวด',
		'area'=>'3',
		'purpose'=>'เอามาให้ผู้ชุมนุมดื่ม',
		'hazardname'=>'น้ำจากเทือกเขา',
		'businessname'=>'น้ำเปล่า',
		'hazardno'=>'514724554446',
		'condition'=>'ต้องเขย่าก่อนดื่ม',
		'expday'=>'12',
		'expmonth'=>'มกราคม',
		'expyear'=>'2556',
		'officername'=>'สมรัก คำสิงค์',
		'certid1'=>'วอ.3-0031/2555',
		'hazardname1'=>'น้ำจากเทือกเขา',
		'businessname1'=>'โซดาไฟ',
		'hazardno1'=>'51675754346',
	);

	$infoz2=array(
		'no'=>'0001',
		'day'=>'12',
		'month'=>'มกราคม',
		'year'=>'2556',
		'name'=>'นายสุเทพ เทือกสุบรรณ',
		'nationality'=>'ไทย',
		'taxno'=>'5410500199',
		'addrhouse'=>'52',
		'addrvillage'=>'1',
		'addrdrive'=>'2',
		'addrroad'=>'เทพกระษัตรี',
		'addrsubdistrict'=>'เทพกระษัตรี',
		'addrdistrict'=>'ถลาง',
		'addrprovince'=>'ภูเก็ต',
		'addrpostalcode'=>'83110',
		'addrphone'=>'076311650',
		'addrfax'=>'076313535',
		'hazardname'=>'น้ำจากเทือกเขา',
		'hazardformulation'=>'H20',
		'businessname'=>'น้ำเปล่า',
		'producer'=>'นาย อากง แซ่ยี้ ผลิตที่ เขาใหญ่',
		'importer'=>'ดร. ภุชงค์ ชงไมโล',
		'saleman'=>'ดร. อานน สว่างวง',
		'purpose'=>'เอามาให้ผู้ชุมนุมดื่ม',
		'container'=>'ถังสังกะษี',	
		'other'=>'-',
		'expday'=>'12',
		'expmonth'=>'มกราคม',
		'expyear'=>'2556',
		'officername'=>'สมรัก คำสิงค์'
	);

	$infoz14=array(
		'no'=>'0001',
		'day'=>'12',
		'month'=>'มกราคม',
		'year'=>'2556',
		'name'=>'นายสุเทพ เทือกสุบรรณ',
		'nationality'=>'ไทย',
		'taxno'=>'5410500199',
		'addrhouse'=>'52',
		'addrvillage'=>'1',
		'addrdrive'=>'2',
		'addrroad'=>'เทพกระษัตรี',
		'addrsubdistrict'=>'เทพกระษัตรี',
		'addrdistrict'=>'ถลาง',
		'addrprovince'=>'ภูเก็ต',
		'addrpostalcode'=>'83110',
		'addrphone'=>'076311650',
		'addrfax'=>'076313535',
		'storehouse'=>'52',
		'storevillage'=>'1',
		'storedrive'=>'2',
		'storeroad'=>'เทพกระษัตรี',
		'storesubdistrict'=>'เทพกระษัตรี',
		'storedistrict'=>'ถลาง',
		'storeprovince'=>'ภูเก็ต',
		'storepostalcode'=>'83110',
		'storephone'=>'076311650',
		'storefax'=>'076313535',
		'hazardname'=>'น้ำจากเทือกเขา',
		'hazardformulation'=>'H20',
		'businessname'=>'น้ำเปล่า',
		'producer'=>'นาย อากง แซ่ยี้ ผลิตที่ เขาใหญ่',
		'importer'=>'ดร. ภุชงค์ ชงไมโล',
		'quantity'=>'5 ถัง กบัอีก 3 ขวด',
		'other'=>'-',
		'expday'=>'12',
		'expmonth'=>'มกราคม',
		'expyear'=>'2556',
		'officername'=>'สมรัก คำสิงค์'
	);

?>

<div class="page-header">
    <h1>ทดสอบการปริ้นเอกสารอนุญาต</h1>
</div>

<div>
	<a class="btnPrint" href='<?php echo resolvePrinterURI("vk2", $info2 );?>'>ทดสอบ วอ.2</a>
</div>
<div>
	<a class="btnPrint" href='<?php echo resolvePrinterURI("vk4", $info4 );?>'>ทดสอบ วอ.4</a>
</div>
<div>
	<a class="btnPrint" href='<?php echo resolvePrinterURI("vk6", $info6 );?>'>ทดสอบ วอ.6</a>
</div>
<div>
	<a class="btnPrint" href='<?php echo resolvePrinterURI("vk8", $info8 );?>'>ทดสอบ วอ.8</a>
</div>
<div>
	<a class="btnPrint" href='<?php echo resolvePrinterURI("vk_ks_kvk2", $infoz2 );?>'>ทดสอบ วอ./กษ./กวก.2</a>
</div>
<div>
	<a class="btnPrint" href='<?php echo resolvePrinterURI("vk_ks_kvk14", $infoz14 );?>'>ทดสอบ วอ./กษ./กวก.14</a>
</div>

<?php
 	include(resolveHeader('includes/footer.php'));
?>